apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rca-api
  namespace: xcmg-rca
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: rca.xcmg.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rca-api
                port:
                  number: 80
  tls:
    - hosts:
        - rca.xcmg.example.com
      secretName: rca-tls-secret
