apiVersion: v1
kind: Service
metadata:
  name: rca-api
  namespace: xcmg-rca
  labels:
    app: rca-api
spec:
  type: ClusterIP
  selector:
    app: rca-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
